name: smart_quiz_helper
description: 智能答题助手 - 基于截图自动识别的答题辅助工具
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI框架
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  
  # 状态管理
  provider: ^6.1.1
  
  # 数据库
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.3
  
  # 网络请求
  dio: ^5.3.2
  
  # OCR和ML（移动端）
  google_ml_kit: ^0.16.3
  
  # 图片处理
  image: ^4.1.3
  image_picker: ^1.0.4
  
  # 权限管理（移动端）
  permission_handler: ^11.0.1
  
  # 文件操作
  path_provider: ^2.1.1
  
  # 系统服务（移动端）
  flutter_local_notifications: ^16.1.0
  device_apps: ^2.2.0
  
  # 浮窗（Android专用）
  flutter_overlay_window: ^0.2.4
  
  # JSON序列化
  json_annotation: ^4.8.1
  
  # 工具类
  uuid: ^3.0.7
  intl: ^0.18.1
  
  # HTTP客户端
  http: ^1.1.0
  
  # 阿里云OCR相关
  crypto: ^3.0.3
  convert: ^3.1.1
  
  # 桌面平台专用依赖
  screen_capturer: ^0.2.1  # 屏幕截图
  window_manager: ^0.3.6   # 窗口管理
  hotkey_manager: ^0.2.2   # 全局热键
  system_tray: ^0.1.1      # 系统托盘
  
  # 跨平台文件对话框
  file_picker: ^6.1.1
  
  # 网页链接处理
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts:
  #   - family: PingFang
  #     fonts:
  #       - asset: assets/fonts/PingFang-Regular.ttf 